- hosts: localhost
  vars:
    pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9dblk/9GGZQmklr0TPcJtgG8c5ikgG3nXj/iAahtIVHjT0jailjvtdspidJnySb5jbJOK6O0654hLaIIqxTxiBu4PwdwrSXbLzk00yZCQNk2+F4aGz3IybMX2DZsPf0ByQ7LC3EcV9q1lLLNVXnzyZMez2+pNuGFNvbvaOpX+5Tgl8lDgcdu05VK8ooWhiFjwkJ3D1+zlszDmJBmwgElHh81SqMtF2SpRB5L4sMvliIjOP59Ie/i21QmBrLzCW1p4I8xPQc5cgDU6Rdn0D8DbbhzoCpRBSw7NQh/9YKxffwmwIlJ5oF7OqSRk2ja9Ktwexnlhq9F//84iFfBGpB7b ellorent@redhat.com
  gather_facts: false
  tasks:
    - name: Generate Zuul SSH key for Nodepool
      command: ssh-keygen -f /var/ssh/nodepool -N ''
      args:
        creates: /var/ssh/nodepool.pub
    - name: Add Nodepool key to node authorized_keys file
      command: cp /var/ssh/nodepool.pub /var/node/authorized_keys
      args:
        creates: /var/node/authorized_keys
